#!/usr/bin/env python
"""
    Convert VSCode's .json themes to Aard2's .css

    Author: Alexander Rusakevich
    2023
"""

__author__ = "Alexander Rusakevich"
__version_arr__ = (0, 0, 1)
__version__ = "v" + ".".join([str(i) for i in __version_arr__])

import os
import json
import datetime
import glob
import colorama
import re
import traceback
import pathlib
from colorama import Fore

colors = {
    "bg_color": "black",
    "font_color": "#a0a0a0",

    "a_color": "#a3964e",
    "a_color_active": "#faa700",
    "a_color_visited": "#735a0a",

    "tr_color": "orangered",
    "pos_color": "green",
    "co_color": "#888888"
}

CSS_BASE = open("base_theme.scss", "r", encoding="utf8").read()


def convert_to_css(file_name: str) -> None:
    theme_file_stem = pathlib.Path(file_name).stem
    css_theme_path = os.path.splitext(file_name)[0] + ".css"

    style_file = None
    with open(file_name, "r", encoding="utf8") as f:
        style_file = json.load(f)

    metainf = json.load(open(os.path.join(".", "themes", "__metainf.json"), "r", encoding="utf8"))[theme_file_stem]

    CSS_HEAD = f"""
/* 
 * Generated by Aard2 theme generator {__version__} (created by {__author__})
 * {str(datetime.datetime.utcnow())}
 *
 * Theme: {style_file.get("name", theme_file_stem)}
 * Type: {style_file["type"]}
 *
 * Original author: {metainf["author"]}
 * Repo: {metainf["repo"]}
 */
""".strip() + (2*"\n")

    file_colors = style_file["colors"]

    colors["bg_color"]           = file_colors["editor.background"]
    colors["font_color"]         = file_colors["editor.foreground"]

    colors["a_color"]            = file_colors["terminal.ansiCyan"]
    colors["a_color_active"]     = file_colors["terminal.ansiBlue"]
    colors["a_color_visited"]    = file_colors["terminal.ansiBrightMagenta"]

    colors["tr_color"]           = file_colors["terminal.ansiYellow"]
    colors["pos_color"]          = file_colors["terminal.ansiGreen"]
    colors["co_color"]           = file_colors["terminal.ansiBrightBlack"]

    with open(css_theme_path, "w", encoding="utf8") as f:
        f.write(CSS_HEAD)

        css_theme_code = CSS_BASE.replace(";", " !important;")
        for k, v in colors.items():
            css_theme_code = re.sub(fr"\${k}(?=\b)", v, css_theme_code)

        f.write(css_theme_code)


def main():
    colorama.init(autoreset=True)

    json_files = [f for f in glob.glob(os.path.join(".", "themes", "*.json")) 
        if not pathlib.Path(f).stem.startswith("__")]
    for json_file in json_files:
        print(f"Generating the theme for '{json_file}'...", end=" ")

        try:
            convert_to_css(json_file)
        except:
            print(Fore.LIGHTRED_EX +  "Fail")
            print(traceback.format_exc())
        else:
            print(Fore.LIGHTGREEN_EX +  "OK")


if __name__ == "__main__":
    main()
