#!/usr/bin/env python
"""
    Convert VSCode's .json themes to Aard2's .css

    Author: Alexander Rusakevich
    2023
"""

import os
import json
import datetime

colors = {
    "bg_color": "black",
    "font_color": "#a0a0a0",

    "a_color": "#a3964e",
    "a_color_visited": "#735a0a",

    "tr_color": "orangered",
    "pos_color": "green",
    "co_color": "#888888"
}

CSS_BASE = """
body {{
    background-color: {bg_color};
    color: {font_color};
}}

a {{
    color: {a_color};
}}

a:visited {{
    color: {a_color_visited};
}}

.tr {{
    color: {tr_color};
}}

.pos {{
    color: {pos_color};
    font-weight: bold;
}}

.co {{
    color: {co_color};
}}
"""

def main():
    file_name = input("Enter vscode .json theme's full path: ")
    css_theme_path = os.path.splitext(file_name)[0] + ".css"

    style_file = None
    with open(file_name, "r", encoding="utf8") as f:
        style_file = json.load(f)

    repo_link = input("Enter original repo link, please: ")

    CSS_HEAD = f"""
/* 
 * Generated by Aard2 theme generator (Alexander Rusakevich)
 * {str(datetime.datetime.utcnow())}
 *
 * Theme: {style_file["name"]}
 * Repo: {repo_link}
 * Type: {style_file["type"]}
 */
""".strip() + (2*"\n")

    colors["bg_color"] = style_file["colors"]["editor.background"]
    colors["font_color"] = style_file["colors"]["editor.foreground"]

    colors["a_color"] = style_file["colors"]["textLink.foreground"]
    colors["a_color_visited"] = style_file["colors"]["textLink.activeForeground"]

    colors["tr_color"] = style_file["colors"]["terminal.ansiYellow"]
    colors["pos_color"] = style_file["colors"]["terminal.ansiGreen"]
    colors["co_color"] = style_file["colors"]["terminal.ansiBrightBlack"]

    with open(css_theme_path, "w", encoding="utf8") as f:
        f.write(CSS_HEAD)
        f.write(CSS_BASE.format(**colors))
    
    print(f"The theme is generated successfully. The file is '{css_theme_path}'")

    

if __name__ == "__main__":
    main()
